[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.28.0"
ci = "github"
installers = ["shell"]
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu",
]
install-path = "CARGO_HOME"
install-updater = false

[dist.github-custom-runners]
runner = "ubuntu-24.04"
aarch64-apple-darwin = "macos-14"
aarch64-unknown-linux-gnu = "ubuntu-24.04"
x86_64-unknown-linux-gnu = "ubuntu-24.04"
